services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    user: 1000:1000
    container_name: filebrowser
    volumes:
      - ${HOME}:/srv #Change to match your directory
      - ${HOME}/docker/filebrowser/filebrowser.db:/filebrowser.db #Change to match your directory
      - ${HOME}/docker/filebrowser/.filebrowser.json:/.filebrowser.json #Change to match your directory
      - ${HOME}/docker/filebrowser/branding:/branding #Change to match your directory
    ports:
      - 8195:80 #Change the port if needed
    restart: always
