services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /home/leandro/:/srv #Change to match your directory
      - /home/leandro/docker/filebrowser/filebrowser.db:/database/filebrowser.db #Change to match your directory
      - /home/leandro/docker/filebrowser/settings.json:/config/settings.json #Change to match your directory
      - /home/leandro/docker/filebrowser/branding:/branding #Change to match your directory
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    ports:
      - 8195:80 #Change the port if needed
